# Generated by Django 6.0.4 on 2026-04-25 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('plaga', 'Análisis de plaga'), ('precio', 'Consulta de precio'), ('clima', 'Consulta de clima'), ('registro', 'Registro de cosecha')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='consultas/')),
                ('respuesta_ia', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('inicio', 'Inicio'), ('esperando_cultivo', 'Esperando cultivo'), ('esperando_cantidad', 'Esperando cantidad'), ('esperando_municipio', 'Esperando municipio')], default='inicio', max_length=30)),
                ('datos_temp', models.JSONField(default=dict)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Puebla', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cultivo_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cultivo')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_propuesto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agricultor')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cultivo')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cultivo')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio')),
            ],
        ),
    ]
