# Generated by Django 6.0.4 on 2026-04-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estadoconversacion_ultimo_mensaje_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('beneficio', models.TextField()),
                ('requisitos', models.TextField()),
                ('contacto', models.CharField(max_length=200)),
                ('vigente', models.BooleanField(default=True)),
            ],
        ),
    ]
