# Generated by Django 6.0.4 on 2026-04-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_programaapoyo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoconversacion',
            name='estado',
            field=models.CharField(choices=[('inicio', 'Inicio'), ('esperando_nombre', 'Esperando nombre'), ('esperando_cultivo', 'Esperando cultivo'), ('esperando_cantidad', 'Esperando cantidad'), ('esperando_municipio', 'Esperando municipio'), ('esperando_editar_campo', 'Esperando campo a editar'), ('esperando_nuevo_valor', 'Esperando nuevo valor')], default='inicio', max_length=30),
        ),
    ]
