# Generated by Django 6.0.4 on 2026-04-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_estadoconversacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoconversacion',
            name='estado',
            field=models.CharField(choices=[('inicio', 'Inicio'), ('esperando_nombre', 'Esperando nombre'), ('esperando_cultivo', 'Esperando cultivo'), ('esperando_cantidad', 'Esperando cantidad'), ('esperando_municipio', 'Esperando municipio'), ('esperando_editar_campo', 'Esperando campo a editar'), ('esperando_nuevo_valor', 'Esperando nuevo valor'), ('esperando_cultivo_planear', 'Esperando cultivo a planear'), ('esperando_municipio_planear', 'Esperando municipio para planear'), ('esperando_kg_vendidos', 'Esperando kg vendidos')], default='inicio', max_length=30),
        ),
    ]
