# Generated by Django 6.0.4 on 2026-04-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_estadoconversacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultor',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
