# Generated by Django 6.0.4 on 2026-04-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agricultor_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosecha',
            name='proceso',
            field=models.CharField(choices=[('sin_procesar', 'Sin procesar'), ('lavado', 'Lavado'), ('natural', 'Natural'), ('honey', 'Honey'), ('anerobic', 'Fermentación Anaeróbica')], default='sin_procesar', max_length=20),
        ),
    ]
